version: '3.3'

volumes:
  postgres_data:
  media_value:
  result_build:
  static_backend_value:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - /home/anzhela/.env
    ports:
      - "5432:5432"

  backend:
    image: anzhelanamistyuk/foodgram:latest

#    build:
#      context: ../backend/api_foodgram
#      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
#      - ../backend/api_foodgram/.env
      - /home/anzhela/.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_backend_value:/var/html/static_backend/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend


